const PRIMARY_COLOR = '#753fd0';
const SECONDARY_COLOR = '#2a2d3e';
const PRIMARY_COLOR_OPACITY = '#753fd011';
const ACTIVE_COLOR = '#10b981';

export { PRIMARY_COLOR, SECONDARY_COLOR, PRIMARY_COLOR_OPACITY, ACTIVE_COLOR };
