export const allLanguages = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Spanish' },
  { value: 'da', label: 'Danish' },
  { value: 'nl', label: 'Dutch' },
  { value: 'lv', label: 'Latvian' },
  { value: 'ua', label: 'Ukrainian' },
  { value: 'cat', label: 'Catalan' },
  { value: 'est', label: 'Estonian' },
  { value: 'cz', label: 'Czech' },
  { value: 'he', label: 'Hebrew' },
  { value: 'ru', label: 'Russian' },
  { value: 'de', label: 'German' },
  { value: 'el', label: 'Greek' },
  { value: 'en-uk', label: 'UK English' },
  { value: 'bg', label: 'Bulgarian' },
  { value: 'fr', label: 'French' },
  { value: 'vi', label: 'Vietnamese' },
];
